<?php

namespace DDB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    public function getPosMax() {
        return $this->createQueryBuilder('a')
                ->select('a, MAX(a.position) as max_pos')
                ->setMaxResults(1)
                ->getQuery()
                ->getResult();
    }
}
