<?php

namespace DDB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * BungalowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BungalowRepository extends EntityRepository
{
    public function findDispo(){
       return $this->createQueryBuilder('a')->where('a.disponible=true');
    }
}
