<?php

namespace DDB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function listePhotobyBungalow($bungalow_id){
        $qb = $this->createQueryBuilder('a')
                ->where('a.bungalowId=:bungalow_id')
                ->setParameter('bungalow_id', $bungalow_id);
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
